In [2]:
for i in range(0, 10, 3):
    print(i)

0
3
6
9


In [11]:
indices = list(range(10))
print(indices)

import random
print(random.shuffle(indices))
print(indices)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None
[4, 8, 6, 5, 9, 1, 2, 3, 0, 7]


In [13]:
import tensorflow as tf
for i in range(0, 10, 3):
    x = tf.constant(indices[i: min(i + 3, 15)])
    print(x)

tf.Tensor([4 8 6], shape=(3,), dtype=int32)
tf.Tensor([5 9 1], shape=(3,), dtype=int32)
tf.Tensor([2 3 0], shape=(3,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int32)
