In [2]:
for i in range(0, 10, 3):
    print(i)

0
3
6
9


In [11]:
indices = list(range(10))
print(indices)

import random
print(random.shuffle(indices))
print(indices)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
None
[4, 8, 6, 5, 9, 1, 2, 3, 0, 7]


In [13]:
import tensorflow as tf
for i in range(0, 10, 3):
    x = tf.constant(indices[i: min(i + 3, 15)])
    print(x)

tf.Tensor([4 8 6], shape=(3,), dtype=int32)
tf.Tensor([5 9 1], shape=(3,), dtype=int32)
tf.Tensor([2 3 0], shape=(3,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int32)


In [4]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = [1,2,3,4,5]
X = np.array(X)
X =  X.reshape(-1, 1)
#向数据集添加多项式特征
poly = PolynomialFeatures(degree=20,include_bias = False)
X_poly = poly.fit_transform(X)
#打印结果
print(X_poly.shape)
print(X_poly)



(5, 20)
[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [2.00000000e+00 4.00000000e+00 8.00000000e+00 1.60000000e+01
  3.20000000e+01 6.40000000e+01 1.28000000e+02 2.56000000e+02
  5.12000000e+02 1.02400000e+03 2.04800000e+03 4.09600000e+03
  8.19200000e+03 1.63840000e+04 3.27680000e+04 6.55360000e+04
  1.31072000e+05 2.62144000e+05 5.24288000e+05 1.04857600e+06]
 [3.00000000e+00 9.00000000e+00 2.70000000e+01 8.10000000e+01
  2.43000000e+02 7.29000000e+02 2.18700000e+03 6.56100000e+03
  1.96830000e+04 5.90490000e+04 1.77147000e+05 5.31441000e+05
  1.59432300e+06 4.78296900e+06 1.43489070e+07 4.30467210e+07
  1.29140163e+08 3.87420489e+08 1.16226147e+09 3.48678440e+09]
 [4.00000000e+00 1.60000000e+01 6.40000000e+01 2.56000000e+