# 实现对简单矩阵的因子分解Matrix Factorization Machine

1. 这个非常重要，是基础技术点。需要弄清楚里面的每一个知识点。
2. 从纯数学的角度来实现这个算法。
3. 采用Tensorflow来对矩阵进行运算。
4. 意义：
   1. 为了解决矩阵稀疏的问题。
   2. 隐性空间维度k。隐性空间是不可解释的。如果k越大说明模型越精细，也就是说将物品的划分的分类越具体；k越小表明模型泛化能力越强。k的大小决定了隐性空间的表达能力。
   3. 如果特征数量大于样本数量时会无法训练。一般情况下都需要选择比较小的k。
   4. 将高维矩阵分解为低维矩阵的乘积。
5. MF的几种方式
   1. 特征值分解：特征值和特征值分解。特征值和特征向量不唯一。
      1. 缺点：只能对方阵使用。
   2. 奇异值分解SVD
   3. 
6. 使用梯度下降来进行求解时，模型的复杂度是$O(kn)$。k是隐性空间维度，n是待分解矩阵维度（需要说明，在视频里面是对一个实对称矩阵进行的分解，所以维度是$n \times n$的）。

In [5]:
import tensorflow as tf
import numpy as np

D_Square = tf.Variable(np.random.rand(3, 3), dtype=float)
D = tf.Variable(np.random.rand(3, 5), dtype=float)

In [6]:
print(D)
print(D_Square)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.26082656, 0.7300368 , 0.20139404, 0.6149434 , 0.8817458 ],
       [0.4932277 , 0.3340946 , 0.5541022 , 0.5025151 , 0.04034995],
       [0.70651567, 0.9423688 , 0.03177893, 0.60564923, 0.0193814 ]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0.6457381 , 0.76257956, 0.3799022 ],
       [0.00645747, 0.39431894, 0.89076203],
       [0.2524235 , 0.30996695, 0.6118661 ]], dtype=float32)>


## 奇异值分解

In [13]:
help(tf.linalg.svd)

Help on function svd in module tensorflow.python.ops.linalg_ops:

svd(tensor, full_matrices=False, compute_uv=True, name=None)
    Computes the singular value decompositions of one or more matrices.
    
    Computes the SVD of each inner matrix in `tensor` such that
    `tensor[..., :, :] = u[..., :, :] * diag(s[..., :, :]) *
     transpose(conj(v[..., :, :]))`
    
    ```python
    # a is a tensor.
    # s is a tensor of singular values.
    # u is a tensor of left singular vectors.
    # v is a tensor of right singular vectors.
    s, u, v = svd(a)
    s = svd(a, compute_uv=False)
    ```
    
    Args:
      tensor: `Tensor` of shape `[..., M, N]`. Let `P` be the minimum of `M` and
        `N`.
      full_matrices: If true, compute full-sized `u` and `v`. If false
        (the default), compute only the leading `P` singular vectors.
        Ignored if `compute_uv` is `False`.
      compute_uv: If `True` then left and right singular vectors will be
        computed and returned in 

In [17]:
S, U, V= tf.linalg.svd(D)
print(S, U, V)

tf.Tensor([1.         0.99999994 0.99999994], shape=(3,), dtype=float32) tf.Tensor(
[[-0.          0.70710677  0.70710677]
 [ 1.          0.         -0.        ]
 [-0.          0.70710677 -0.70710677]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 1.          0.          0.        ]
 [ 0.          0.70710677 -0.70710677]
 [ 0.          0.70710677  0.70710677]], shape=(3, 3), dtype=float32)


In [20]:
print(tf.matmul(U,V))

tf.Tensor(
[[ 0.00000000e+00  9.99999940e-01  1.26880515e-08]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.26880515e-08 -9.99999940e-01]], shape=(3, 3), dtype=float32)


In [ ]:
# 指定分解的隐藏维度
k = 3

