# Tensorflow基本操作

1. 使用的tensorflow版本是2.8.0 
2. 参考视频<https://www.bilibili.com/video/BV1Ub4y1e7P3?p=4>
3. **重点-参考网页**<https://zhuanlan.zhihu.com/p/377280469>

In [1]:
import tensorflow as tf
import numpy as np

# 6 * 5矩阵
R = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0],
     [0,3,2,4,1]])

# 方阵
R_Square = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0]])

## 创建指定大小的矩阵

1. 创建全零的tensor矩阵

In [ ]:
m =5
K = 4
n = 7
# 方法一
P = tf.zeros([m, K], dtype=float)
Q = tf.zeros([K, n], dtype=float)

2. 创建指定大小的tensor矩阵。**推荐**

In [ ]:
# 方法二
P = tf.Variable(np.random.rand(m, K), dtype=float)
Q = tf.Variable(np.random.rand(K, n), dtype=float)

## 将np.array转换为tensor

In [2]:
R_tf = tf.convert_to_tensor(R, dtype=float)
R_Square_tf = tf.convert_to_tensor(R_Square, dtype=float)

## 获取tensor的形状

In [3]:
R_tf.shape

TensorShape([6, 5])

## 读取tensor矩阵指定位置的值

In [4]:
R_tf[1][3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [5]:
R_tf[1, 3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

## 读取指定行

In [6]:
R_tf[1, :]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 1., 3., 5.], dtype=float32)>

## 读取指定列

In [7]:
R_tf[:,2]

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 3., 0., 4., 2.], dtype=float32)>

## 修改tensor的形状

1. 若有一个维度为-1，那么tensorflow会自动推导。
2. tf.reshape(tensor, shape, name=None)
    1. tensor：要改变维度（形状）的张量；
    2. shape：希望变成什么维度；
    3. name：操作的名称。

In [8]:
P = tf.reshape(R_tf[1, :], [1, -1])
print(P.shape)

(1, 5)


In [9]:

Q = tf.reshape(R_tf[:,2], [-1, 1])
print(Q.shape)

(6, 1)


## 矩阵之间乘法

In [10]:
eui = tf.matmul(tf.reshape(R_Square_tf[2, :], [1, -1]),tf.reshape(R_Square_tf[:, 3], [-1, 1])) - R_Square_tf[2,3]
print(eui)

tf.Tensor([[19.]], shape=(1, 1), dtype=float32)


## 矩阵之间数乘

1. 计算的是矩阵每个对应位置元素相乘。
2. 需要两个矩阵形状一样。

In [11]:
tf.multiply(R_Square_tf[2, :], R_Square_tf[3, :])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8., 15.,  0.,  2.,  0.], dtype=float32)>

## 数乘以矩阵

In [12]:
a = 3
print(a * R_Square_tf)

tf.Tensor(
[[12.  0.  3.  0. 15.]
 [ 3.  6.  3.  9. 15.]
 [12. 15.  9.  3.  0.]
 [ 6.  9.  0.  6. 15.]
 [15.  3. 12.  0.  0.]], shape=(5, 5), dtype=float32)


## tensor类型判断

In [13]:
isinstance(eui, tf.Tensor)

True

In [14]:
tf.is_tensor(eui)

True

In [15]:
tf.is_tensor(R)

False

In [16]:
eui.dtype == tf.int16

False

In [17]:
eui.dtype == tf.float32

True

## tensor的类型转换

1. 参考网页<https://wenku.baidu.com/view/9a3b8439fc00bed5b9f3f90f76c66137ef064f55.html>

In [18]:
# 这些都是错误的，在tf 2.0之后都不支持了。

# 将字符串转化为tf.float32（默认）和tf.int32
# tf.string_to_number(string_tensor, out_type=None, name=None)

# 转化为tf.float64
# tf.to_double(eui, name='ToDouble')

# 转化为tf.float32
# tf.to_float(eui, name='ToFloat')

# 转化为tf.int32
# tf.to_int32(eui, name='ToInt32')

# 转化为tf.int64
# tf.to_int64(eui, name='ToInt64')

# 转化为dtype指定的类型
# tf.cast(x, dtype, name=None)

In [19]:
x_0 = np.arange(5)
print(x_0)
x_1 = tf.convert_to_tensor(x_0, dtype=tf.int32)
print(x_1)
x_2 = tf.cast(x_1, dtype=tf.float32)
print(x_2)
x_3 = tf.cast(x_2, dtype=tf.int32)
print(x_3)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## 矩阵计算平方

1. 计算的是每个元素的平方值
2. tf.math还有这个类，下面应该有很多数学方法。

In [20]:
eui_square = tf.square(eui)
print(eui_square)

tf.Tensor([[361.]], shape=(1, 1), dtype=float32)


In [21]:
R_tf_square = tf.square(R_tf)
print(R_tf_square)

tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1.  4.  1.  9. 25.]
 [16. 25.  9.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## 计算tensor所有行或者所有列的和

1. 使用tf.reduce_sum来完成
2. 建议都需要填写keepdims=True参数，用于保证tensor的形状。

In [22]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [23]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    This is the reduction operation for the elementwise `tf.math.add` op.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    of the entries in `axis`, which must be unique. If `keepdims` is true, the
    reduced dimensions are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
      >>> # x has a shape of (2, 3) (two rows and three columns):
      >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
      >>> x.numpy()
      array([[1, 1, 1],
             [1, 1, 1]], dtype=int32)
      >>> # sum all the elements
      >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
      >>> tf.reduce_sum(x).numpy()
      

In [24]:
# 按行求和
row_sum = tf.reduce_sum(R_tf, 1, keepdims=True)
print(row_sum)

tf.Tensor(
[[10.]
 [12.]
 [13.]
 [12.]
 [10.]
 [10.]], shape=(6, 1), dtype=float32)


In [25]:
# 按列求和
column_sum = tf.reduce_sum(R_tf, 0, keepdims=True)
print(column_sum)

tf.Tensor([[16. 14. 11. 10. 16.]], shape=(1, 5), dtype=float32)


In [26]:
# 对所有元素求总和

total_sum = tf.reduce_sum(tf.reduce_sum(R_tf, 0))
print(total_sum)

tf.Tensor(67.0, shape=(), dtype=float32)


## 修改tensor指定位置的值

1. 重点-参考网址<https://blog.csdn.net/qq_34418352/article/details/106399327>
2. tensor本身不能直接修改指定位置的值，需要转化为Variable之后，配合assign（动词，分配的意思）一起来完成这个操作。
3. 使用的是tf.Variable.assign和tf.Variable.assign_add来进行修改。也就是说支队tensorflow variable类型才能使用。<https://www.jianshu.com/p/efcb86940896>

### 修改指定位置的值第一种方法

In [27]:
R_tf_square_variable = tf.Variable(R_tf_square)
R_tf_square_variable[1, 1].assign(99)
print(R_tf_square_variable) 

<tf.Variable 'Variable:0' shape=(6, 5) dtype=float32, numpy=
array([[16.,  0.,  1.,  0., 25.],
       [ 1., 99.,  1.,  9., 25.],
       [16., 25.,  9.,  1.,  0.],
       [ 4.,  9.,  0.,  4., 25.],
       [25.,  1., 16.,  0.,  0.],
       [ 0.,  9.,  4., 16.,  1.]], dtype=float32)>


### 修改指定位置的值第二种方法

1. 这种方法也太不直接了。

In [28]:
def ModifyTensor(input_tensor, position=None, value=None):
    input_tensor = input_tensor.numpy()
    input_tensor[tuple(position)] = value
    return input_tensor
# new_tensor
R_tf_square_variable = tf.py_function(ModifyTensor, inp=[R_tf_square_variable, [2,2], 44], 
                            Tout=R_tf_square_variable.dtype)
print(type(R_tf_square_variable))
print(R_tf_square_variable)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1. 99.  1.  9. 25.]
 [16. 25. 44.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## tensor变量的定义及使用

1. 定义标量

In [47]:
a = tf.Variable(1.0)
b = (a + 2) * 3
print(b)

tf.Tensor(9.0, shape=(), dtype=float32)


2. 定义矩阵变量
3. 修改特定位置的值
4. 修改一行值

In [81]:
a = tf.Variable(np.random.rand(3, 5), dtype=float)
print(a)
a[1, 1].assign(5)
print(a)
a[2, :].assign(tf.constant([1.0, 2.0, 3.0, 4.0, 5.0]))
print(a)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.537704  , 0.6189068 , 0.30331826, 0.04615806, 0.9390641 ],
       [0.4411376 , 0.77692914, 0.66065925, 0.54005116, 0.8708451 ],
       [0.8276978 , 0.05360403, 0.6741581 , 0.75516224, 0.7454265 ]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.537704  , 0.6189068 , 0.30331826, 0.04615806, 0.9390641 ],
       [0.4411376 , 5.        , 0.66065925, 0.54005116, 0.8708451 ],
       [0.8276978 , 0.05360403, 0.6741581 , 0.75516224, 0.7454265 ]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.537704  , 0.6189068 , 0.30331826, 0.04615806, 0.9390641 ],
       [0.4411376 , 5.        , 0.66065925, 0.54005116, 0.8708451 ],
       [1.        , 2.        , 3.        , 4.        , 5.        ]],
      dtype=float32)>


5. tf.Variable.assign_add的使用。

In [45]:
a = tf.Variable(1.0)
b = (a.assign_add(2)) * 3
print(b)

tf.Tensor(9.0, shape=(), dtype=float32)


6. 循环访问tensor变量中的值

In [64]:
m = 3
K = 5
P = tf.Variable(np.random.rand(m, K), dtype=float)

for i in range(m):
    print("Display P[i, :].shape={} and P[i, :]={}".format(P[i, :].shape, P[i, :]))

for j in range(K):
    print("Display P[:, j].shape={} and P[:, j]={}".format(P[i, :].shape, P[:, j]))

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.8150224 , 0.7282639 , 0.742883  , 0.27481833, 0.24528237],
       [0.50891954, 0.59461313, 0.30716848, 0.44362485, 0.83934766],
       [0.572105  , 0.22647381, 0.90912443, 0.9687402 , 0.01386218]],
      dtype=float32)>
tf.Tensor(
[[0.7282639 ]
 [0.59461313]
 [0.22647381]], shape=(3, 1), dtype=float32)
Display P[i, :].shape=(5,) and P[i, :]=[0.8150224  0.7282639  0.742883   0.27481833 0.24528237]
Display P[i, :].shape=(5,) and P[i, :]=[0.50891954 0.59461313 0.30716848 0.44362485 0.83934766]
Display P[i, :].shape=(5,) and P[i, :]=[0.572105   0.22647381 0.90912443 0.9687402  0.01386218]
Display P[:, j].shape=(5,) and P[:, j]=[0.8150224  0.50891954 0.572105  ]
Display P[:, j].shape=(5,) and P[:, j]=[0.7282639  0.59461313 0.22647381]
Display P[:, j].shape=(5,) and P[:, j]=[0.742883   0.30716848 0.90912443]
Display P[:, j].shape=(5,) and P[:, j]=[0.27481833 0.44362485 0.9687402 ]
Display P[:, j].shape=(5,) and P[:, j]=[0

7. 修改指定行，不能用=来进行赋值。必须用assign来赋值。

In [73]:
P[1,:].assign(P[1,:] + P[0,:])
P[1,:] = P[1,:] + P[0,:]
print(P[1,:])
print(P)

tf.Tensor([2.426511   1.0461559  0.55837667 0.8844567  0.91170746], shape=(5,), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.9751168 , 0.45239753, 0.22370517, 0.09391819, 0.15972255],
       [2.426511  , 1.0461559 , 0.55837667, 0.8844567 , 0.91170746],
       [0.7278972 , 0.66830045, 0.1793684 , 0.6468218 , 0.531055  ]],
      dtype=float32)>


8. 修改指定列
这个地方要与第9点进行比较，并没有出现将列拿出来单独计算时的问题！！！

In [74]:
print(P)

P[:, 0].assign(P[:, 0] + P[:, 1])
print(P)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.9751168 , 0.45239753, 0.22370517, 0.09391819, 0.15972255],
       [2.426511  , 1.0461559 , 0.55837667, 0.8844567 , 0.91170746],
       [0.7278972 , 0.66830045, 0.1793684 , 0.6468218 , 0.531055  ]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[1.4275143 , 0.45239753, 0.22370517, 0.09391819, 0.15972255],
       [3.472667  , 1.0461559 , 0.55837667, 0.8844567 , 0.91170746],
       [1.3961977 , 0.66830045, 0.1793684 , 0.6468218 , 0.531055  ]],
      dtype=float32)>


9. **读取tensor矩阵中的一列时，直接读取出来的维度不对！需要使用reshape来调整维度**。

在读取一个维度的时候，读取出来的是3个标量，而不是1*3的向量！！！在做乘法的时候表现出来了。

In [91]:
m = 3
n = 5
P = tf.Variable(np.random.rand(m, n), dtype=float)

# 注意两者的维度不同！！！
print(P[:,1])
print(tf.reshape(P[:,1], [3,1]))

tf.Tensor([0.02205932 0.3810846  0.84163105], shape=(3,), dtype=float32)
tf.Tensor(
[[0.02205932]
 [0.3810846 ]
 [0.84163105]], shape=(3, 1), dtype=float32)


注意！！ c是一个2维的矩阵，只不过维度是[1,1]。这个和直接P[1,1]有区别！！！而且这两个值不能直接进行计算！

In [92]:
c = tf.matmul(tf.reshape(P[:,1], [1,m]), tf.reshape(P[:,1], [m,1]))
print(c)

d = c - tf.Variable(1.0)
print(d)

tf.Tensor([[0.8540549]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.14594507]], shape=(1, 1), dtype=float32)


注意这个报错！就不能将一个二维矩阵赋值给一个标量。
但是按一般的理解P[1,1]取出来的值也应该是一个二维矩阵，但tensorflow做了严格的区分。
只能通过c[0,0]来转换一下再进行赋值。

In [98]:
P[1,1].assign(c)

UnimplementedError: sliced l-value shape [] does not match r-value shape [1,1]. Automatic broadcasting not yet implemented. [Op:ResourceStridedSliceAssign] name: strided_slice/_assign

In [99]:
P[1,1].assign(c[0,0])

<tf.Variable 'UnreadVariable' shape=(3, 5) dtype=float32, numpy=
array([[0.02021691, 0.02205932, 0.9237868 , 0.32626224, 0.36083788],
       [0.69728947, 0.8540549 , 0.22294073, 0.50841606, 0.7523607 ],
       [0.1233462 , 0.84163105, 0.33912864, 0.5408292 , 0.43469703]],
      dtype=float32)>

10. tensor之间比较大小

In [55]:
a = tf.Variable(2.0)
b = tf.Variable(1.0)

if a > b:
    print("a > b")

a > b


11. tensor与数值之间比较大小

In [57]:
a = tf.Variable(2.0)
b = 1.0

print(type(a))
print(type(b))

if a > b:
    print("a > b")

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'float'>
a > b


12. tf.slice的使用

In [82]:
a = tf.Variable(np.random.rand(3, 5), dtype=float)

In [83]:
sr = tf.slice(a, [0,0], [1,5])
print(sr)
print(type(sr))
print(sr.shape)

tf.Tensor([[0.9060171  0.07738302 0.46185705 0.59008974 0.82741785]], shape=(1, 5), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 5)


In [84]:
sc = tf.slice(a, [0,0], [3,1])
print(sc)
print(type(sc))
print(sc.shape)

tf.Tensor(
[[0.9060171 ]
 [0.02471187]
 [0.6643875 ]], shape=(3, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3, 1)


切片了之后无法赋值！！！！！！！！

In [87]:
so = tf.slice(a, [0,0], [1,1])
print(so)
print(type(so))
print(so.shape)

so = 44
print(a)

tf.Tensor([[0.9060171]], shape=(1, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 1)
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.9060171 , 0.07738302, 0.46185705, 0.59008974, 0.82741785],
       [0.02471187, 0.98970073, 0.97137535, 0.721932  , 0.97627556],
       [0.6643875 , 0.8575097 , 0.9728985 , 0.7265927 , 0.24499872]],
      dtype=float32)>


## tensor可以与数值比较大小

In [29]:
if 1999 > eui_square:
    print("OK")
else:
    print("Fail")

OK


## 查看tensor矩阵的值

In [32]:
print(P.eval)

<bound method BaseResourceVariable.eval of <tf.Variable 'Variable:0' shape=(5, 4) dtype=float32, numpy=
array([[0.18259706, 0.34361672, 0.29749665, 0.15125796],
       [0.81373745, 0.08230656, 0.56470615, 0.9131422 ],
       [0.5198513 , 0.40072557, 0.99874765, 0.38617522],
       [0.60281074, 0.3949722 , 0.4758499 , 0.31637025],
       [0.85923576, 0.49117374, 0.80321246, 0.0234599 ]], dtype=float32)>>


## 求向量的范数

In [33]:
help(tf.norm)

Help on function norm_v2 in module tensorflow.python.ops.linalg_ops:

norm_v2(tensor, ord='euclidean', axis=None, keepdims=None, name=None)
    Computes the norm of vectors, matrices, and tensors.
    
    This function can compute several different vector norms (the 1-norm, the
    Euclidean or 2-norm, the inf-norm, and in general the p-norm for p > 0) and
    matrix norms (Frobenius, 1-norm, 2-norm and inf-norm).
    
    Args:
      tensor: `Tensor` of types `float32`, `float64`, `complex64`, `complex128`
      ord: Order of the norm. Supported values are `'fro'`, `'euclidean'`,
        `1`, `2`, `np.inf` and any positive real number yielding the corresponding
        p-norm. Default is `'euclidean'` which is equivalent to Frobenius norm if
        `tensor` is a matrix and equivalent to 2-norm for vectors.
        Some restrictions apply:
          a) The Frobenius norm `'fro'` is not defined for vectors,
          b) If axis is a 2-tuple (matrix norm), only `'euclidean'`, '`fro'`, 

In [34]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [35]:
# 计算的是向量的。
row_vector = tf.reshape(R_tf[0, :], [1, -1])
print(row_vector)

L1 = tf.norm(row_vector, ord=1)
print(L1)

L2 = tf.norm(row_vector, ord=2)
print(L2)

tf.Tensor([[4. 0. 1. 0. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(6.4807405, shape=(), dtype=float32)


In [36]:
# 计算矩阵所有行或者所有列的范数。

# 按列求L1范数
L1_matrix = tf.norm(R_tf, ord=1, axis=0)
print(L1_matrix)

# 按行求L2范数
L2_matrix = tf.norm(R_tf, ord=2, axis=1)
print(L2_matrix)

tf.Tensor([16. 14. 11. 10. 16.], shape=(5,), dtype=float32)
tf.Tensor([6.4807405 6.3245554 7.141428  6.4807405 6.4807405 5.477226 ], shape=(6,), dtype=float32)


## 求矩阵的逆

In [37]:
help(tf.linalg.inv)

Help on function matrix_inverse in module tensorflow.python.ops.gen_linalg_ops:

matrix_inverse(input, adjoint=False, name=None)
    Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
    
    
    The input is a tensor of shape `[..., M, M]` whose inner-most 2 dimensions
    form square matrices. The output is a tensor of the same shape as the input
    containing the inverse for all input submatrices `[..., :, :]`.
    
    The op uses LU decomposition with partial pivoting to compute the inverses.
    
    If a matrix is not invertible there is no guarantee what the op does. It
    may detect the condition and raise an exception or it may simply return a
    garbage result.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float64`, `float32`, `half`, `complex64`, `complex128`.
        Shape is `[..., M, M]`.
      adjoint: An optional `bool`. Defaults to `False`.
      name: A name for the operation (o

In [38]:
print(tf.linalg.inv(R_Square_tf))

tf.Tensor(
[[-0.8799998  -0.8399998  -0.92        1.7199999   1.12      ]
 [ 0.39999998  0.19999999  0.6000001  -0.6        -0.6       ]
 [ 0.99999976  0.99999976  0.99999994 -1.9999998  -0.99999994]
 [-1.4799998  -0.6399999  -1.3200002   2.12        1.5200001 ]
 [ 0.7039999   0.47199994  0.536      -0.9759999  -0.696     ]], shape=(5, 5), dtype=float32)


## 求矩阵的转置

In [39]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
    

In [40]:
print(tf.transpose(R_tf))

tf.Tensor(
[[4. 1. 4. 2. 5. 0.]
 [0. 2. 5. 3. 1. 3.]
 [1. 1. 3. 0. 4. 2.]
 [0. 3. 1. 2. 0. 4.]
 [5. 5. 0. 5. 0. 1.]], shape=(5, 6), dtype=float32)


## 生成单位矩阵

In [41]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

## 对矩阵求导

In [ ]:
matrix_will_grad = tf.Variable(np.random.rand(3, 5), dtype=float)


## 对矩阵求偏导