# Tensorflow基本操作

1. 使用的tensorflow版本是2.8.0 
2. 参考视频<https://www.bilibili.com/video/BV1Ub4y1e7P3?p=4>
3. **重点-参考网页**<https://zhuanlan.zhihu.com/p/377280469>

In [23]:
import tensorflow as tf
import numpy as np

# 6 * 5矩阵
R = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0],
     [0,3,2,4,1]])

# 方阵
R_Square = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0]])

## 将np.array转换为tensor

In [24]:
R_tf = tf.convert_to_tensor(R, dtype=float)
R_Square_tf = tf.convert_to_tensor(R_Square, dtype=float)

## 获取tensor的形状

In [16]:
R_tf.shape

TensorShape([6, 5])

## 读取tensor矩阵指定位置的值

In [11]:
R_tf[1][3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [21]:
R_tf[1, 3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

## 读取指定行

In [13]:
R_tf[1, :]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 1., 3., 5.], dtype=float32)>

## 读取指定列

In [14]:
R_tf[:,2]

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 3., 0., 4., 2.], dtype=float32)>

## 修改tensor的形状

1. 若有一个维度为-1，那么tensorflow会自动推导。
2. tf.reshape(tensor, shape, name=None)
    1. tensor：要改变维度（形状）的张量；
    2. shape：希望变成什么维度；
    3. name：操作的名称。

In [19]:
P = tf.reshape(R_tf[1, :], [1, -1])
print(P.shape)

(1, 5)


In [20]:

Q = tf.reshape(R_tf[:,2], [-1, 1])
print(Q.shape)

(6, 1)


## 矩阵乘法

In [25]:
eui = tf.matmul(tf.reshape(R_Square_tf[2, :], [1, -1]),tf.reshape(R_Square_tf[:, 3], [-1, 1])) - R_Square_tf[2,3]
print(eui)

tf.Tensor([[19.]], shape=(1, 1), dtype=float32)


## 矩阵数乘

1. 计算的是矩阵每个对应位置元素相乘。
2. 需要两个矩阵形状一样。

In [29]:
tf.multiply(R_Square_tf[2, :], R_Square_tf[3, :])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8., 15.,  0.,  2.,  0.], dtype=float32)>

## 矩阵计算平方

1. 计算的是每个元素的平方值
2. tf.math还有这个类，下面应该有很多数学方法。

In [26]:
eui_square = tf.square(eui)
print(eui_square)

tf.Tensor([[361.]], shape=(1, 1), dtype=float32)


In [27]:
R_tf_square = tf.square(R_tf)
print(R_tf_square)

tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1.  4.  1.  9. 25.]
 [16. 25.  9.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## 修改tensor指定位置的值

1. 重点-参考网址<https://blog.csdn.net/qq_34418352/article/details/106399327>
2. tensor本身不能直接修改指定位置的值，需要转化为Variable之后，配合assign（动词，分配的意思）一起来完成这个操作。

In [32]:
R_tf_square_variable = tf.Variable(R_tf_square)
R_tf_square_variable[1, 1].assign(99)
print(R_tf_square_variable) 

<tf.Variable 'Variable:0' shape=(6, 5) dtype=float32, numpy=
array([[16.,  0.,  1.,  0., 25.],
       [ 1., 99.,  1.,  9., 25.],
       [16., 25.,  9.,  1.,  0.],
       [ 4.,  9.,  0.,  4., 25.],
       [25.,  1., 16.,  0.,  0.],
       [ 0.,  9.,  4., 16.,  1.]], dtype=float32)>


In [36]:
def ModifyTensor(input_tensor, position=None, value=None):
    input_tensor = input_tensor.numpy()
    input_tensor[tuple(position)] = value
    return input_tensor
# new_tensor
R_tf_square_variable = tf.py_function(ModifyTensor, inp=[R_tf_square_variable, [2,2], 44], 
                            Tout=R_tf_square_variable.dtype)
print(type(R_tf_square_variable))
print(R_tf_square_variable)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1. 99.  1.  9. 25.]
 [16. 25. 55.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## tensor可以与数值比较大小

In [31]:
if 1999 > eui_square:
    print("OK")
else:
    print("Fail")

OK


## 创建指定大小的矩阵

In [8]:
m =5
K = 4
n = 7
P = tf.zeros([m, K], dtype=float)
Q = tf.zeros([K, n], dtype=float)

## 查看tensor矩阵的值

In [9]:
print(P.eval)

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>>
