# Tensorflow基本操作

1. 使用的tensorflow版本是2.8.0 
2. 参考视频<https://www.bilibili.com/video/BV1Ub4y1e7P3?p=4>
3. **重点-参考网页**<https://zhuanlan.zhihu.com/p/377280469>

In [1]:
import tensorflow as tf
import numpy as np

# 6 * 5矩阵
R = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0],
     [0,3,2,4,1]])

# 方阵
R_Square = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0]])

## 将np.array转换为tensor

In [2]:
R_tf = tf.convert_to_tensor(R, dtype=float)
R_Square_tf = tf.convert_to_tensor(R_Square, dtype=float)

## 获取tensor的形状

In [3]:
R_tf.shape

TensorShape([6, 5])

## 读取tensor矩阵指定位置的值

In [4]:
R_tf[1][3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [5]:
R_tf[1, 3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

## 读取指定行

In [6]:
R_tf[1, :]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 1., 3., 5.], dtype=float32)>

## 读取指定列

In [7]:
R_tf[:,2]

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 3., 0., 4., 2.], dtype=float32)>

## 修改tensor的形状

1. 若有一个维度为-1，那么tensorflow会自动推导。
2. tf.reshape(tensor, shape, name=None)
    1. tensor：要改变维度（形状）的张量；
    2. shape：希望变成什么维度；
    3. name：操作的名称。

In [8]:
P = tf.reshape(R_tf[1, :], [1, -1])
print(P.shape)

(1, 5)


In [9]:

Q = tf.reshape(R_tf[:,2], [-1, 1])
print(Q.shape)

(6, 1)


## 矩阵之间乘法

In [10]:
eui = tf.matmul(tf.reshape(R_Square_tf[2, :], [1, -1]),tf.reshape(R_Square_tf[:, 3], [-1, 1])) - R_Square_tf[2,3]
print(eui)

tf.Tensor([[19.]], shape=(1, 1), dtype=float32)


## 矩阵之间数乘

1. 计算的是矩阵每个对应位置元素相乘。
2. 需要两个矩阵形状一样。

In [43]:
tf.multiply(R_Square_tf[2, :], R_Square_tf[3, :])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8., 15.,  0.,  2.,  0.], dtype=float32)>

## 数乘以矩阵

In [42]:
a = 3
print(a * R_Square_tf)

tf.Tensor(
[[12.  0.  3.  0. 15.]
 [ 3.  6.  3.  9. 15.]
 [12. 15.  9.  3.  0.]
 [ 6.  9.  0.  6. 15.]
 [15.  3. 12.  0.  0.]], shape=(5, 5), dtype=float32)


## tensor类型判断

In [11]:
isinstance(eui, tf.Tensor)

True

In [12]:
tf.is_tensor(eui)

True

In [13]:
tf.is_tensor(R)

False

In [14]:
eui.dtype == tf.int16

False

In [15]:
eui.dtype == tf.float32

True

## tensor的类型转换

1. 参考网页<https://wenku.baidu.com/view/9a3b8439fc00bed5b9f3f90f76c66137ef064f55.html>

In [16]:
# 这些都是错误的，在tf 2.0之后都不支持了。

# 将字符串转化为tf.float32（默认）和tf.int32
# tf.string_to_number(string_tensor, out_type=None, name=None)

# 转化为tf.float64
# tf.to_double(eui, name='ToDouble')

# 转化为tf.float32
# tf.to_float(eui, name='ToFloat')

# 转化为tf.int32
# tf.to_int32(eui, name='ToInt32')

# 转化为tf.int64
# tf.to_int64(eui, name='ToInt64')

# 转化为dtype指定的类型
# tf.cast(x, dtype, name=None)

In [17]:
x_0 = np.arange(5)
print(x_0)
x_1 = tf.convert_to_tensor(x_0, dtype=tf.int32)
print(x_1)
x_2 = tf.cast(x_1, dtype=tf.float32)
print(x_2)
x_3 = tf.cast(x_2, dtype=tf.int32)
print(x_3)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## 矩阵计算平方

1. 计算的是每个元素的平方值
2. tf.math还有这个类，下面应该有很多数学方法。

In [19]:
eui_square = tf.square(eui)
print(eui_square)

tf.Tensor([[361.]], shape=(1, 1), dtype=float32)


In [20]:
R_tf_square = tf.square(R_tf)
print(R_tf_square)

tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1.  4.  1.  9. 25.]
 [16. 25.  9.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## 计算tensor所有行或者所有列的和

1. 使用tf.reduce_sum来完成
2. 建议都需要填写keepdims=True参数，用于保证tensor的形状。

In [21]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [22]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    This is the reduction operation for the elementwise `tf.math.add` op.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    of the entries in `axis`, which must be unique. If `keepdims` is true, the
    reduced dimensions are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
      >>> # x has a shape of (2, 3) (two rows and three columns):
      >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
      >>> x.numpy()
      array([[1, 1, 1],
             [1, 1, 1]], dtype=int32)
      >>> # sum all the elements
      >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
      >>> tf.reduce_sum(x).numpy()
      

In [23]:
# 按行求和
row_sum = tf.reduce_sum(R_tf, 1, keepdims=True)
print(row_sum)

tf.Tensor(
[[10.]
 [12.]
 [13.]
 [12.]
 [10.]
 [10.]], shape=(6, 1), dtype=float32)


In [24]:
# 按列求和
column_sum = tf.reduce_sum(R_tf, 0, keepdims=True)
print(column_sum)

tf.Tensor([[16. 14. 11. 10. 16.]], shape=(1, 5), dtype=float32)


In [40]:
# 对所有元素求总和

total_sum = tf.reduce_sum(tf.reduce_sum(R_tf, 0))
print(total_sum)

tf.Tensor(67.0, shape=(), dtype=float32)


## 修改tensor指定位置的值

1. 重点-参考网址<https://blog.csdn.net/qq_34418352/article/details/106399327>
2. tensor本身不能直接修改指定位置的值，需要转化为Variable之后，配合assign（动词，分配的意思）一起来完成这个操作。

In [25]:
R_tf_square_variable = tf.Variable(R_tf_square)
R_tf_square_variable[1, 1].assign(99)
print(R_tf_square_variable) 

<tf.Variable 'Variable:0' shape=(6, 5) dtype=float32, numpy=
array([[16.,  0.,  1.,  0., 25.],
       [ 1., 99.,  1.,  9., 25.],
       [16., 25.,  9.,  1.,  0.],
       [ 4.,  9.,  0.,  4., 25.],
       [25.,  1., 16.,  0.,  0.],
       [ 0.,  9.,  4., 16.,  1.]], dtype=float32)>


In [26]:
def ModifyTensor(input_tensor, position=None, value=None):
    input_tensor = input_tensor.numpy()
    input_tensor[tuple(position)] = value
    return input_tensor
# new_tensor
R_tf_square_variable = tf.py_function(ModifyTensor, inp=[R_tf_square_variable, [2,2], 44], 
                            Tout=R_tf_square_variable.dtype)
print(type(R_tf_square_variable))
print(R_tf_square_variable)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1. 99.  1.  9. 25.]
 [16. 25. 44.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## tensor可以与数值比较大小

In [27]:
if 1999 > eui_square:
    print("OK")
else:
    print("Fail")

OK


## 创建指定大小的矩阵

In [28]:
m =5
K = 4
n = 7
# 方法一
P = tf.zeros([m, K], dtype=float)
Q = tf.zeros([K, n], dtype=float)

In [29]:
# 方法二
P = tf.Variable(np.random.rand(m, K), dtype=float)
Q = tf.Variable(np.random.rand(K, n), dtype=float)

## 查看tensor矩阵的值

In [30]:
print(P.eval)

<bound method BaseResourceVariable.eval of <tf.Variable 'Variable:0' shape=(5, 4) dtype=float32, numpy=
array([[0.9598642 , 0.5326815 , 0.22479562, 0.25738415],
       [0.30663824, 0.72301006, 0.29180887, 0.7215307 ],
       [0.20874037, 0.88132447, 0.45667493, 0.9683734 ],
       [0.36923876, 0.11047538, 0.49011227, 0.4392923 ],
       [0.7609648 , 0.45308602, 0.21007618, 0.7738772 ]], dtype=float32)>>


## 求向量的范数

In [31]:
help(tf.norm)

Help on function norm_v2 in module tensorflow.python.ops.linalg_ops:

norm_v2(tensor, ord='euclidean', axis=None, keepdims=None, name=None)
    Computes the norm of vectors, matrices, and tensors.
    
    This function can compute several different vector norms (the 1-norm, the
    Euclidean or 2-norm, the inf-norm, and in general the p-norm for p > 0) and
    matrix norms (Frobenius, 1-norm, 2-norm and inf-norm).
    
    Args:
      tensor: `Tensor` of types `float32`, `float64`, `complex64`, `complex128`
      ord: Order of the norm. Supported values are `'fro'`, `'euclidean'`,
        `1`, `2`, `np.inf` and any positive real number yielding the corresponding
        p-norm. Default is `'euclidean'` which is equivalent to Frobenius norm if
        `tensor` is a matrix and equivalent to 2-norm for vectors.
        Some restrictions apply:
          a) The Frobenius norm `'fro'` is not defined for vectors,
          b) If axis is a 2-tuple (matrix norm), only `'euclidean'`, '`fro'`, 

In [37]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [38]:
# 计算的是向量的。
row_vector = tf.reshape(R_tf[0, :], [1, -1])
print(row_vector)

L1 = tf.norm(row_vector, ord=1)
print(L1)

L2 = tf.norm(row_vector, ord=2)
print(L2)

tf.Tensor([[4. 0. 1. 0. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(6.4807405, shape=(), dtype=float32)


In [36]:
# 计算矩阵所有行或者所有列的范数。

# 按列求L1范数
L1_matrix = tf.norm(R_tf, ord=1, axis=0)
print(L1_matrix)

# 按行求L2范数
L2_matrix = tf.norm(R_tf, ord=2, axis=1)
print(L2_matrix)

tf.Tensor([16. 14. 11. 10. 16.], shape=(5,), dtype=float32)
tf.Tensor([6.4807405 6.3245554 7.141428  6.4807405 6.4807405 5.477226 ], shape=(6,), dtype=float32)


## 求矩阵的逆

In [47]:
help(tf.linalg.inv)

Help on function matrix_inverse in module tensorflow.python.ops.gen_linalg_ops:

matrix_inverse(input, adjoint=False, name=None)
    Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
    
    
    The input is a tensor of shape `[..., M, M]` whose inner-most 2 dimensions
    form square matrices. The output is a tensor of the same shape as the input
    containing the inverse for all input submatrices `[..., :, :]`.
    
    The op uses LU decomposition with partial pivoting to compute the inverses.
    
    If a matrix is not invertible there is no guarantee what the op does. It
    may detect the condition and raise an exception or it may simply return a
    garbage result.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float64`, `float32`, `half`, `complex64`, `complex128`.
        Shape is `[..., M, M]`.
      adjoint: An optional `bool`. Defaults to `False`.
      name: A name for the operation (o

In [48]:
print(tf.linalg.inv(R_Square_tf))

tf.Tensor(
[[-0.8799998  -0.8399998  -0.92        1.7199999   1.12      ]
 [ 0.39999998  0.19999999  0.6000001  -0.6        -0.6       ]
 [ 0.99999976  0.99999976  0.99999994 -1.9999998  -0.99999994]
 [-1.4799998  -0.6399999  -1.3200002   2.12        1.5200001 ]
 [ 0.7039999   0.47199994  0.536      -0.9759999  -0.696     ]], shape=(5, 5), dtype=float32)


## 求矩阵的转置

In [51]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
    

In [52]:
print(tf.transpose(R_tf))

tf.Tensor(
[[4. 1. 4. 2. 5. 0.]
 [0. 2. 5. 3. 1. 3.]
 [1. 1. 3. 0. 4. 2.]
 [0. 3. 1. 2. 0. 4.]
 [5. 5. 0. 5. 0. 1.]], shape=(5, 6), dtype=float32)


## 生成单位矩阵

In [53]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>