# Tensorflow基本操作

1. 使用的tensorflow版本是2.8.0 
2. 参考视频<https://www.bilibili.com/video/BV1Ub4y1e7P3?p=4>
3. **重点-参考网页**<https://zhuanlan.zhihu.com/p/377280469>

In [1]:
import tensorflow as tf
import numpy as np

# 6 * 5矩阵
R = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0],
     [0,3,2,4,1]])

# 方阵
R_Square = np.array([[4,0,1,0,5],
     [1,2,1,3,5],
     [4,5,3,1,0],
     [2,3,0,2,5],
     [5,1,4,0,0]])

## 创建指定大小的矩阵

推荐使用第二种和第三种方法。

1. 创建全零的tensor矩阵

In [2]:
m =5
K = 4
n = 7
# 方法一
P = tf.zeros([m, K], dtype=float)
Q = tf.zeros([K, n], dtype=float)

2. 创建指定大小的tensor矩阵。**推荐**

In [3]:
# 方法二
P = tf.Variable(np.random.rand(m, K), dtype=float)
Q = tf.Variable(np.random.rand(K, n), dtype=float)
print(P)

<tf.Variable 'Variable:0' shape=(5, 4) dtype=float32, numpy=
array([[0.43144086, 0.85016817, 0.50062466, 0.14131236],
       [0.77002394, 0.2379001 , 0.83680534, 0.8187988 ],
       [0.44617015, 0.19982924, 0.8027723 , 0.79939735],
       [0.09975889, 0.40954486, 0.16605115, 0.19585085],
       [0.48539668, 0.2297538 , 0.28419298, 0.73151916]], dtype=float32)>


3. **推荐**。使用tensorflow自己的函数创建随机产生的矩阵。而且矩阵中数值的分布满足每个元素都从均值为0、标准差为1的标准高斯分布。

In [4]:
P = tf.random.normal(shape=[3, 4])
print(P)

tf.Tensor(
[[ 7.9705125e-01 -9.1456337e-04  7.6800370e-01 -1.0291841e+00]
 [ 4.8757440e-01  2.0260191e-02  2.3996034e+00  7.4235994e-01]
 [-1.7365299e-01  5.6161481e-01  1.0555596e-01 -1.4153365e+00]], shape=(3, 4), dtype=float32)


4. 创建全1矩阵

In [5]:
AE = tf.ones(shape=[3,4])
AE

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

5. 创建单位矩阵

对角矩阵是方阵，一般记为$diag(a_1,a_2,\cdots,a_n)$。\
单位矩阵是对角矩阵的特例，所有对角线上的元素全为1。\
tf可以创建不是方阵的在$i=j$的位置上的类似对角矩阵的矩阵。

In [6]:
E = tf.eye(3)
E

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [7]:
E_other = tf.eye(3,5)
E_other

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

## 将np.array转换为tensor

In [8]:
R_tf = tf.convert_to_tensor(R, dtype=float)
R_Square_tf = tf.convert_to_tensor(R_Square, dtype=float)

## 获取tensor的形状

In [9]:
R_tf.shape

TensorShape([6, 5])

## 获取tensor的长度

通过os.len()实际上获取的是矩阵或者向量第一个维度的值。\
\
对于向量获取的是元素个数。\
对于2维矩阵获取的是行数。\
对于3维矩阵获取的也是行数。

In [112]:
print(R_tf)
print(len(R_tf))

tf.Tensor(
[[4. 0. 1. 0. 5.]
 [1. 2. 1. 3. 5.]
 [4. 5. 3. 1. 0.]
 [2. 3. 0. 2. 5.]
 [5. 1. 4. 0. 0.]
 [0. 3. 2. 4. 1.]], shape=(6, 5), dtype=float32)
6


In [113]:
T = tf.ones([2,3,4])
print(T)
print(len(T))

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
2


## 获取tensor中元素的个数

In [10]:
tf.size(R_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

## 读取tensor矩阵指定位置的值

In [11]:
R_tf[1][3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [12]:
R_tf[1, 3]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

## 读取指定行

In [13]:
R_tf[1, :]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 1., 3., 5.], dtype=float32)>

## 读取指定列

In [14]:
R_tf[:,2]

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 3., 0., 4., 2.], dtype=float32)>

## 修改tensor的形状

1. 若有一个维度为-1，那么tensorflow会自动推导。
2. tf.reshape(tensor, shape, name=None)
    1. tensor：要改变维度（形状）的张量；
    2. shape：希望变成什么维度；
    3. name：操作的名称。

In [15]:
P = tf.reshape(R_tf[1, :], [1, -1])
print(P.shape)

(1, 5)


In [16]:

Q = tf.reshape(R_tf[:,2], [-1, 1])
print(Q.shape)

(6, 1)


## tensor之间的运算有两种
1. 按元素的运算
2. 按线性代数之间的预算

In [17]:
P = tf.ones([3, 4], dtype=float)
Q = tf.random.normal(shape=[3, 4])
print(P,Q)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[-0.375439   -0.7055323   0.8676633  -0.86653954]
 [-2.541676    0.9290615   0.8484637  -0.8516716 ]
 [ 1.0396664   0.10289904 -1.3224237  -0.5521795 ]], shape=(3, 4), dtype=float32)


### 按元素加

In [18]:
P + Q

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.624561  ,  0.2944677 ,  1.8676634 ,  0.13346046],
       [-1.541676  ,  1.9290614 ,  1.8484638 ,  0.14832842],
       [ 2.0396664 ,  1.1028991 , -0.3224237 ,  0.44782048]],
      dtype=float32)>

### 按元素减

In [19]:
P - Q

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3754389 ,  1.7055323 ,  0.13233668,  1.8665395 ],
       [ 3.541676  ,  0.07093853,  0.15153629,  1.8516716 ],
       [-0.03966641,  0.8971009 ,  2.3224237 ,  1.5521796 ]],
      dtype=float32)>

### 按元素乘法

In [20]:
P * Q

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.375439  , -0.7055323 ,  0.8676633 , -0.86653954],
       [-2.541676  ,  0.9290615 ,  0.8484637 , -0.8516716 ],
       [ 1.0396664 ,  0.10289904, -1.3224237 , -0.5521795 ]],
      dtype=float32)>

### 按元素除法

In [21]:
P / Q

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-2.6635487 , -1.4173695 ,  1.1525208 , -1.1540154 ],
       [-0.39344117,  1.0763551 ,  1.1786008 , -1.1741616 ],
       [ 0.961847  ,  9.718264  , -0.7561873 , -1.8110052 ]],
      dtype=float32)>

### 按元素求幂

In [22]:
tf.exp(Q)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.68698764, 0.4938456 , 2.38134   , 0.42040384],
       [0.07873433, 2.5321314 , 2.3360553 , 0.42670107],
       [2.8282733 , 1.1083795 , 0.26648864, 0.57569367]], dtype=float32)>

### 按元素判断tensor比较大小、判断是否相等，返回的是每个位置的boolen型值。

In [23]:
P == Q

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [24]:
P < Q

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])>

In [25]:
P > Q

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])>

### 按元素对tensor所有元素求和

In [26]:
tf.reduce_sum(P)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

## 矩阵之间乘法

In [27]:
eui = tf.matmul(tf.reshape(R_Square_tf[2, :], [1, -1]),tf.reshape(R_Square_tf[:, 3], [-1, 1])) - R_Square_tf[2,3]
print(eui)

tf.Tensor([[19.]], shape=(1, 1), dtype=float32)


## 矩阵之间数乘

1. 计算的是矩阵每个对应位置元素相乘。
2. 需要两个矩阵形状一样。

In [28]:
tf.multiply(R_Square_tf[2, :], R_Square_tf[3, :])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8., 15.,  0.,  2.,  0.], dtype=float32)>

## 数乘以矩阵

In [29]:
a = 3
print(a * R_Square_tf)

tf.Tensor(
[[12.  0.  3.  0. 15.]
 [ 3.  6.  3.  9. 15.]
 [12. 15.  9.  3.  0.]
 [ 6.  9.  0.  6. 15.]
 [15.  3. 12.  0.  0.]], shape=(5, 5), dtype=float32)


## tensor类型判断

In [30]:
isinstance(eui, tf.Tensor)

True

In [31]:
tf.is_tensor(eui)

True

In [32]:
tf.is_tensor(R)

False

In [33]:
eui.dtype == tf.int16

False

In [34]:
eui.dtype == tf.float32

True

## tensor的类型转换

1. 参考网页<https://wenku.baidu.com/view/9a3b8439fc00bed5b9f3f90f76c66137ef064f55.html>

In [35]:
# 这些都是错误的，在tf 2.0之后都不支持了。

# 将字符串转化为tf.float32（默认）和tf.int32
# tf.string_to_number(string_tensor, out_type=None, name=None)

# 转化为tf.float64
# tf.to_double(eui, name='ToDouble')

# 转化为tf.float32
# tf.to_float(eui, name='ToFloat')

# 转化为tf.int32
# tf.to_int32(eui, name='ToInt32')

# 转化为tf.int64
# tf.to_int64(eui, name='ToInt64')

# 转化为dtype指定的类型
# tf.cast(x, dtype, name=None)

In [36]:
x_0 = np.arange(5)
print(x_0)
x_1 = tf.convert_to_tensor(x_0, dtype=tf.int32)
print(x_1)
x_2 = tf.cast(x_1, dtype=tf.float32)
print(x_2)
x_3 = tf.cast(x_2, dtype=tf.int32)
print(x_3)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## 矩阵计算平方

1. 计算的是每个元素的平方值
2. tf.math还有这个类，下面应该有很多数学方法。

In [37]:
eui_square = tf.square(eui)
print(eui_square)

tf.Tensor([[361.]], shape=(1, 1), dtype=float32)


In [38]:
R_tf_square = tf.square(R_tf)
print(R_tf_square)

tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1.  4.  1.  9. 25.]
 [16. 25.  9.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## 计算tensor所有行或者所有列的和

1. 使用tf.reduce_sum来完成
2. 建议都需要填写keepdims=True参数，用于保证tensor的形状。

In [39]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [40]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    This is the reduction operation for the elementwise `tf.math.add` op.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    of the entries in `axis`, which must be unique. If `keepdims` is true, the
    reduced dimensions are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
      >>> # x has a shape of (2, 3) (two rows and three columns):
      >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
      >>> x.numpy()
      array([[1, 1, 1],
             [1, 1, 1]], dtype=int32)
      >>> # sum all the elements
      >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
      >>> tf.reduce_sum(x).numpy()
      

In [41]:
# 按行求和
row_sum = tf.reduce_sum(R_tf, 1, keepdims=True)
print(row_sum)

tf.Tensor(
[[10.]
 [12.]
 [13.]
 [12.]
 [10.]
 [10.]], shape=(6, 1), dtype=float32)


In [42]:
# 按列求和
column_sum = tf.reduce_sum(R_tf, 0, keepdims=True)
print(column_sum)

tf.Tensor([[16. 14. 11. 10. 16.]], shape=(1, 5), dtype=float32)


In [43]:
# 对所有元素求总和

total_sum = tf.reduce_sum(tf.reduce_sum(R_tf, 0))
print(total_sum)

tf.Tensor(67.0, shape=(), dtype=float32)


## 修改tensor指定位置的值

1. 重点-参考网址<https://blog.csdn.net/qq_34418352/article/details/106399327>
2. tensor本身不能直接修改指定位置的值，需要转化为Variable之后，配合assign（动词，分配的意思）一起来完成这个操作。
3. 使用的是tf.Variable.assign和tf.Variable.assign_add来进行修改。也就是说支队tensorflow variable类型才能使用。<https://www.jianshu.com/p/efcb86940896>

### 修改指定位置的值第一种方法

In [44]:
R_tf_square_variable = tf.Variable(R_tf_square)
R_tf_square_variable[1, 1].assign(99)
print(R_tf_square_variable) 

<tf.Variable 'Variable:0' shape=(6, 5) dtype=float32, numpy=
array([[16.,  0.,  1.,  0., 25.],
       [ 1., 99.,  1.,  9., 25.],
       [16., 25.,  9.,  1.,  0.],
       [ 4.,  9.,  0.,  4., 25.],
       [25.,  1., 16.,  0.,  0.],
       [ 0.,  9.,  4., 16.,  1.]], dtype=float32)>


### 修改指定位置的值第二种方法

1. 这种方法也太不直接了。不建议使用。

In [45]:
def ModifyTensor(input_tensor, position=None, value=None):
    input_tensor = input_tensor.numpy()
    input_tensor[tuple(position)] = value
    return input_tensor
# new_tensor
R_tf_square_variable = tf.py_function(ModifyTensor, inp=[R_tf_square_variable, [2,2], 44], 
                            Tout=R_tf_square_variable.dtype)
print(type(R_tf_square_variable))
print(R_tf_square_variable)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[16.  0.  1.  0. 25.]
 [ 1. 99.  1.  9. 25.]
 [16. 25. 44.  1.  0.]
 [ 4.  9.  0.  4. 25.]
 [25.  1. 16.  0.  0.]
 [ 0.  9.  4. 16.  1.]], shape=(6, 5), dtype=float32)


## tensor变量的定义及使用

1. 定义标量

In [46]:
a = tf.Variable(1.0)
b = (a + 2) * 3
print(b)

tf.Tensor(9.0, shape=(), dtype=float32)


2. 定义矩阵变量
3. 修改特定位置的值
4. 修改一行值

In [47]:
a = tf.Variable(np.random.rand(3, 5), dtype=float)
print(a)
a[1, 1].assign(5)
print(a)
a[2, :].assign(tf.constant([1.0, 2.0, 3.0, 4.0, 5.0]))
print(a)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.26801476, 0.1535667 , 0.0712911 , 0.04843451, 0.6471752 ],
       [0.44910797, 0.95876855, 0.32208735, 0.13650386, 0.4854029 ],
       [0.4881721 , 0.51031166, 0.6748007 , 0.11212479, 0.94872445]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.26801476, 0.1535667 , 0.0712911 , 0.04843451, 0.6471752 ],
       [0.44910797, 5.        , 0.32208735, 0.13650386, 0.4854029 ],
       [0.4881721 , 0.51031166, 0.6748007 , 0.11212479, 0.94872445]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.26801476, 0.1535667 , 0.0712911 , 0.04843451, 0.6471752 ],
       [0.44910797, 5.        , 0.32208735, 0.13650386, 0.4854029 ],
       [1.        , 2.        , 3.        , 4.        , 5.        ]],
      dtype=float32)>


5. tf.Variable.assign_add的使用。

In [48]:
a = tf.Variable(1.0)
b = (a.assign_add(2)) * 3
print(b)

tf.Tensor(9.0, shape=(), dtype=float32)


6. 循环访问tensor变量中的值

In [49]:
m = 3
K = 5
P = tf.Variable(np.random.rand(m, K), dtype=float)

for i in range(m):
    print("Display P[i, :].shape={} and P[i, :]={}".format(P[i, :].shape, P[i, :]))

for j in range(K):
    print("Display P[:, j].shape={} and P[:, j]={}".format(P[i, :].shape, P[:, j]))

Display P[i, :].shape=(5,) and P[i, :]=[0.91882783 0.0759024  0.92322785 0.02995001 0.8881097 ]
Display P[i, :].shape=(5,) and P[i, :]=[0.182659   0.95950633 0.79451627 0.5247518  0.01154005]
Display P[i, :].shape=(5,) and P[i, :]=[0.6942809  0.34874028 0.45080623 0.28575063 0.06420353]
Display P[:, j].shape=(5,) and P[:, j]=[0.91882783 0.182659   0.6942809 ]
Display P[:, j].shape=(5,) and P[:, j]=[0.0759024  0.95950633 0.34874028]
Display P[:, j].shape=(5,) and P[:, j]=[0.92322785 0.79451627 0.45080623]
Display P[:, j].shape=(5,) and P[:, j]=[0.02995001 0.5247518  0.28575063]
Display P[:, j].shape=(5,) and P[:, j]=[0.8881097  0.01154005 0.06420353]


7. 修改指定行，不能用=来进行赋值。必须用assign来赋值。

In [50]:
P[1,:].assign(P[1,:] + P[0,:])
# P[1,:] = P[1,:] + P[0,:]
# print(P[1,:])
# print(P)

<tf.Variable 'UnreadVariable' shape=(3, 5) dtype=float32, numpy=
array([[0.91882783, 0.0759024 , 0.92322785, 0.02995001, 0.8881097 ],
       [1.1014868 , 1.0354087 , 1.7177441 , 0.5547018 , 0.89964974],
       [0.6942809 , 0.34874028, 0.45080623, 0.28575063, 0.06420353]],
      dtype=float32)>

8. 修改指定列
这个地方要与第9点进行比较，并没有出现将列拿出来单独计算时的问题！！！

In [51]:
print(P)

P[:, 0].assign(P[:, 0] + P[:, 1])
print(P)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.91882783, 0.0759024 , 0.92322785, 0.02995001, 0.8881097 ],
       [1.1014868 , 1.0354087 , 1.7177441 , 0.5547018 , 0.89964974],
       [0.6942809 , 0.34874028, 0.45080623, 0.28575063, 0.06420353]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.99473023, 0.0759024 , 0.92322785, 0.02995001, 0.8881097 ],
       [2.1368957 , 1.0354087 , 1.7177441 , 0.5547018 , 0.89964974],
       [1.0430212 , 0.34874028, 0.45080623, 0.28575063, 0.06420353]],
      dtype=float32)>


9. **读取tensor矩阵中的一列时，直接读取出来的维度不对！需要使用reshape来调整维度**。

在读取一个维度的时候，读取出来的是3个标量，而不是1*3的向量！！！在做乘法的时候表现出来了。

In [52]:
m = 3
n = 5
P = tf.Variable(np.random.rand(m, n), dtype=float)

# 注意两者的维度不同！！！
print(P[:,1])
print(tf.reshape(P[:,1], [3,1]))

tf.Tensor([0.57025856 0.4053715  0.2647269 ], shape=(3,), dtype=float32)
tf.Tensor(
[[0.57025856]
 [0.4053715 ]
 [0.2647269 ]], shape=(3, 1), dtype=float32)


注意！！ c是一个2维的矩阵，只不过维度是[1,1]。这个和直接P[1,1]有区别！！！而且这两个值不能直接进行计算！

In [53]:
c = tf.matmul(tf.reshape(P[:,1], [1,m]), tf.reshape(P[:,1], [m,1]))
print(c)

d = c - tf.Variable(1.0)
print(d)

tf.Tensor([[0.5596012]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.4403988]], shape=(1, 1), dtype=float32)


注意这个报错！就不能将一个二维矩阵赋值给一个标量。
但是按一般的理解P[1,1]取出来的值也应该是一个二维矩阵，但tensorflow做了严格的区分。
只能通过c[0,0]来转换一下再进行赋值。

In [54]:
print(P, c)
print(P[1,1])
# P[1,1].assign(c)
# print(P, c)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.6211364 , 0.57025856, 0.85768   , 0.16790171, 0.76152724],
       [0.5395178 , 0.4053715 , 0.8894003 , 0.63968676, 0.3847038 ],
       [0.8028148 , 0.2647269 , 0.5983037 , 0.63252807, 0.6088181 ]],
      dtype=float32)> tf.Tensor([[0.5596012]], shape=(1, 1), dtype=float32)
tf.Tensor(0.4053715, shape=(), dtype=float32)


可以将一个值赋值给矩阵中指定的位置的值。

In [55]:
d = 1.4
print(P, d)
P[1,1].assign(d)
print(P, d)

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.6211364 , 0.57025856, 0.85768   , 0.16790171, 0.76152724],
       [0.5395178 , 0.4053715 , 0.8894003 , 0.63968676, 0.3847038 ],
       [0.8028148 , 0.2647269 , 0.5983037 , 0.63252807, 0.6088181 ]],
      dtype=float32)> 1.4
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.6211364 , 0.57025856, 0.85768   , 0.16790171, 0.76152724],
       [0.5395178 , 1.4       , 0.8894003 , 0.63968676, 0.3847038 ],
       [0.8028148 , 0.2647269 , 0.5983037 , 0.63252807, 0.6088181 ]],
      dtype=float32)> 1.4


In [56]:
P[1,1].assign(c[0,0])

<tf.Variable 'UnreadVariable' shape=(3, 5) dtype=float32, numpy=
array([[0.6211364 , 0.57025856, 0.85768   , 0.16790171, 0.76152724],
       [0.5395178 , 0.5596012 , 0.8894003 , 0.63968676, 0.3847038 ],
       [0.8028148 , 0.2647269 , 0.5983037 , 0.63252807, 0.6088181 ]],
      dtype=float32)>

10. tensor之间比较大小

In [57]:
a = tf.Variable(2.0)
b = tf.Variable(1.0)

if a > b:
    print("a > b")

a > b


11. tensor与数值之间比较大小

In [58]:
a = tf.Variable(2.0)
b = 1.0

print(type(a))
print(type(b))

if a > b:
    print("a > b")

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'float'>
a > b


12. tf.slice的使用

In [59]:
a = tf.Variable(np.random.rand(3, 5), dtype=float)

In [60]:
sr = tf.slice(a, [0,0], [1,5])
print(sr)
print(type(sr))
print(sr.shape)

tf.Tensor([[0.4955216  0.55671823 0.9319378  0.9532316  0.1546873 ]], shape=(1, 5), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 5)


In [61]:
sc = tf.slice(a, [0,0], [3,1])
print(sc)
print(type(sc))
print(sc.shape)

tf.Tensor(
[[0.4955216 ]
 [0.44926876]
 [0.26596218]], shape=(3, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3, 1)


切片了之后无法赋值！！！！！！！！

In [62]:
so = tf.slice(a, [0,0], [1,1])
print(so)
print(type(so))
print(so.shape)

so = 44
print(a)

tf.Tensor([[0.4955216]], shape=(1, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 1)
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[0.4955216 , 0.55671823, 0.9319378 , 0.9532316 , 0.1546873 ],
       [0.44926876, 0.68685144, 0.30435973, 0.96370775, 0.95880693],
       [0.26596218, 0.20282783, 0.06525303, 0.6754675 , 0.5663379 ]],
      dtype=float32)>


## 切片和索引

tensorflow对tensor的处理可以向numpy一样。

In [63]:
P = tf.random.normal(shape=[3, 5])
print(P)

tf.Tensor(
[[ 1.138094    0.39117828 -0.10791022  1.555232    0.7438391 ]
 [-0.38289082 -0.49445543  0.4139752  -0.73416686  0.4170466 ]
 [-1.0501405   0.03855523  0.75220084 -0.43975762 -0.55680084]], shape=(3, 5), dtype=float32)


In [64]:
P[-1], P[1:3]

(<tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([-1.0501405 ,  0.03855523,  0.75220084, -0.43975762, -0.55680084],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.38289082, -0.49445543,  0.4139752 , -0.73416686,  0.4170466 ],
        [-1.0501405 ,  0.03855523,  0.75220084, -0.43975762, -0.55680084]],
       dtype=float32)>)

对矩阵中的多个元素进行赋值。

In [65]:
X_var = tf.Variable(P)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[12.        , 12.        , 12.        , 12.        , 12.        ],
       [12.        , 12.        , 12.        , 12.        , 12.        ],
       [-1.0501405 ,  0.03855523,  0.75220084, -0.43975762, -0.55680084]],
      dtype=float32)>

## tensor可以与数值比较大小

In [66]:
if 1999 > eui_square:
    print("OK")
else:
    print("Fail")

OK


## 查看tensor矩阵的值

In [67]:
print(P.eval)

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 1.138094  ,  0.39117828, -0.10791022,  1.555232  ,  0.7438391 ],
       [-0.38289082, -0.49445543,  0.4139752 , -0.73416686,  0.4170466 ],
       [-1.0501405 ,  0.03855523,  0.75220084, -0.43975762, -0.55680084]],
      dtype=float32)>>


## 求向量的范数

In [68]:
help(tf.norm)

Help on function norm_v2 in module tensorflow.python.ops.linalg_ops:

norm_v2(tensor, ord='euclidean', axis=None, keepdims=None, name=None)
    Computes the norm of vectors, matrices, and tensors.
    
    This function can compute several different vector norms (the 1-norm, the
    Euclidean or 2-norm, the inf-norm, and in general the p-norm for p > 0) and
    matrix norms (Frobenius, 1-norm, 2-norm and inf-norm).
    
    Args:
      tensor: `Tensor` of types `float32`, `float64`, `complex64`, `complex128`
      ord: Order of the norm. Supported values are `'fro'`, `'euclidean'`,
        `1`, `2`, `np.inf` and any positive real number yielding the corresponding
        p-norm. Default is `'euclidean'` which is equivalent to Frobenius norm if
        `tensor` is a matrix and equivalent to 2-norm for vectors.
        Some restrictions apply:
          a) The Frobenius norm `'fro'` is not defined for vectors,
          b) If axis is a 2-tuple (matrix norm), only `'euclidean'`, '`fro'`, 

In [69]:
R_tf

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[4., 0., 1., 0., 5.],
       [1., 2., 1., 3., 5.],
       [4., 5., 3., 1., 0.],
       [2., 3., 0., 2., 5.],
       [5., 1., 4., 0., 0.],
       [0., 3., 2., 4., 1.]], dtype=float32)>

In [70]:
# 计算的是向量的。
row_vector = tf.reshape(R_tf[0, :], [1, -1])
print(row_vector)

L1 = tf.norm(row_vector, ord=1)
print(L1)

L2 = tf.norm(row_vector, ord=2)
print(L2)

tf.Tensor([[4. 0. 1. 0. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(6.4807405, shape=(), dtype=float32)


In [71]:
# 计算矩阵所有行或者所有列的范数。

# 按列求L1范数
L1_matrix = tf.norm(R_tf, ord=1, axis=0)
print(L1_matrix)

# 按行求L2范数
L2_matrix = tf.norm(R_tf, ord=2, axis=1)
print(L2_matrix)

tf.Tensor([16. 14. 11. 10. 16.], shape=(5,), dtype=float32)
tf.Tensor([6.4807405 6.3245554 7.141428  6.4807405 6.4807405 5.477226 ], shape=(6,), dtype=float32)


## 求矩阵的逆

In [72]:
help(tf.linalg.inv)

Help on function matrix_inverse in module tensorflow.python.ops.gen_linalg_ops:

matrix_inverse(input, adjoint=False, name=None)
    Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
    
    
    The input is a tensor of shape `[..., M, M]` whose inner-most 2 dimensions
    form square matrices. The output is a tensor of the same shape as the input
    containing the inverse for all input submatrices `[..., :, :]`.
    
    The op uses LU decomposition with partial pivoting to compute the inverses.
    
    If a matrix is not invertible there is no guarantee what the op does. It
    may detect the condition and raise an exception or it may simply return a
    garbage result.
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float64`, `float32`, `half`, `complex64`, `complex128`.
        Shape is `[..., M, M]`.
      adjoint: An optional `bool`. Defaults to `False`.
      name: A name for the operation (o

In [73]:
print(tf.linalg.inv(R_Square_tf))

tf.Tensor(
[[-0.8799998  -0.8399998  -0.92        1.7199999   1.12      ]
 [ 0.39999998  0.19999999  0.6000001  -0.6        -0.6       ]
 [ 0.99999976  0.99999976  0.99999994 -1.9999998  -0.99999994]
 [-1.4799998  -0.6399999  -1.3200002   2.12        1.5200001 ]
 [ 0.7039999   0.47199994  0.536      -0.9759999  -0.696     ]], shape=(5, 5), dtype=float32)


## 求矩阵的转置

In [74]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
    

In [75]:
print(tf.transpose(R_tf))

tf.Tensor(
[[4. 1. 4. 2. 5. 0.]
 [0. 2. 5. 3. 1. 3.]
 [1. 1. 3. 0. 4. 2.]
 [0. 3. 1. 2. 0. 4.]
 [5. 5. 0. 5. 0. 1.]], shape=(5, 6), dtype=float32)


## 生成单位矩阵

In [76]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

## 对矩阵求导

1. 对一元方程求导。参考<https://blog.csdn.net/AwesomeP/article/details/123787448>

在这里定义了一个变量x，使用tf.variable()声明，与普通张量一样，该变量拥有形状、类型和值这3种属性。变量与普通张量的一个重要区别是，它默认能够被Tensorflow的自动求导机制求导，因此常用于定义机器模型的参数。

补充知识:tf.Variable () 将变量标记为“可训练”，**被标记的变量会在反向传播中记录梯度信息。神经网络训练中，常用该函数标记待训练参数**。

In [77]:
import tensorflow as tf  # tf为2.*版本
x = tf.Variable(initial_value = 3.0) # 定义变量x，初始化为3
with tf.GradientTape() as tape: # 在tf.GradientTape()的上下文中，所有的计算步骤都会被记录，用以求导
    y = tf.square(x) # y = x的平方
y_grad = tape.gradient(y,x) # 计算y关于x的导数
print(y)      # 输出3的平方  tf.Tensor(9.0, shape=(), dtype=float32)
print(y_grad)


tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


上面的例子中使用了tf.Variable()定义x，下面我们展示使用tf.constant()定义x，注意两者之间求导时的不同，需要tape.watch(x)

In [78]:
import tensorflow as tf  
x = tf.constant(3.0) 
with tf.GradientTape(persistent=True) as tape:  # 注意使用persistent=True
    tape.watch(x) 
    y = tf.square(x)    # y = x的平方
    z = tf.pow(x,4)     # z = x的4次方
y_grad = tape.gradient(y,x) 
Z_grad = tape.gradient(z,x)
print(y.numpy())       # 9.0， 我们将tensor类型转换为numpy类型
print(y_grad.numpy())  # 6.0

print(z.numpy())       # 81.0
print(Z_grad.numpy())  # 108.0

9.0
6.0
81.0
108.0


In [79]:
import tensorflow as tf  
x = tf.Variable(3.0) 
with tf.GradientTape(persistent=True) as tape:  # 注意使用persistent=True
    y = tf.square(x)    # y = x的平方
    z = tf.pow(x,4)     # z = x的4次方
y_grad = tape.gradient(y,x) 
Z_grad = tape.gradient(z,x)
print(y.numpy())       # 9.0， 我们将tensor类型转换为numpy类型
print(y_grad.numpy())  # 6.0

print(z.numpy())       # 81.0
print(Z_grad.numpy())  # 108.0

9.0
6.0
81.0
108.0


2. 对多元函数求偏导

In [80]:
matrix_will_grad = tf.Variable(np.random.rand(3, 5), dtype=float)


## 对矩阵求偏导

## 广播机制

理解：当两个向量的形状不符合向量（矩阵的试验不成功）计算的规则时
1. 将两个向量分别按照二元计算的两个向量的形状进行扩展，变成为相同的形状。
2. 然后将两个向量再进行二元计算。

如下面的例子所示，将A只有一列，B只有一行。A按照B的行数进行复制，B按照A的列数进行复制，然后都形成$3 \times 2$的矩阵在进行加法计算。

<https://zh-v2.d2l.ai/chapter_preliminaries/ndarray.html>中的说明如下：我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：首先，通过适当复制元素来扩展一个或两个数组， 以便在转换之后，两个张量具有相同的形状。 其次，对生成的数组执行按元素操作。

In [81]:
A = tf.reshape(tf.range(3), (3, 1))
B = tf.reshape(tf.range(2), (1, 2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [82]:
A + B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [83]:
C = tf.ones([2,2])
D = tf.ones([3,3])
C, D

# 这个时候C和D不能使用广播机制来进行计算。
# C + D

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

## 节省内存

这部分看到了代码但是还不理解作用。
现在的理解是：定义一个变量，python给它分配了一块内存。经过一个运算之后，再次给这个变量赋值时，变量指向了另外一块地址。而原来定义变量时分配的内容没有释放。而tensorflow直接解决了这个问题。

In [84]:
X = tf.random.normal(shape=[3,5])
Y = tf.ones([3,5])

1. python的例子。

<https://zh-v2.d2l.ai/chapter_preliminaries/ndarray.html>说明如下：在下面的例子中，我们用Python的id()函数演示了这一点， 它给我们提供了内存中引用对象的确切地址。 运行Y = Y + X后，我们会发现id(Y)指向另一个位置。**这是因为Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置**。

In [85]:
before = id(Y)
Y = Y + X
id(Y) == before

False

2. tensorflow的例子。

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。 在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。 通常情况下，我们希望原地执行这些更新。 其次，如果我们不原地更新，其他引用仍然会指向旧的内存位置， 这样我们的某些代码可能会无意中引用旧的参数。

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。 在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。 通常情况下，我们希望原地执行这些更新。 其次，如果我们不原地更新，其他引用仍然会指向旧的内存位置， 这样我们的某些代码可能会无意中引用旧的参数。

Variables是TensorFlow中的可变容器，它们提供了一种存储模型参数的方法。 我们可以通过assign将一个操作的结果分配给一个Variable。 为了说明这一点，我们创建了一个与另一个张量Y相同的形状的Z， 使用zeros_like来分配一个全0的块。

In [86]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 1622265288
id(Z): 1622265288


即使你将状态持久存储在Variable中， 你也可能希望避免为不是模型参数的张量过度分配内存，从而进一步减少内存使用量。

由于TensorFlow的Tensors是不可变的，而且梯度不会通过Variable流动， 因此TensorFlow没有提供一种明确的方式来原地运行单个操作。

但是，TensorFlow提供了tf.function修饰符， 将计算封装在TensorFlow图中，该图在运行前经过编译和优化。 这允许TensorFlow删除未使用的值，并复用先前分配的且不再需要的值。 这样可以最大限度地减少TensorFlow计算的内存开销。

In [87]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # 这个未使用的值将被删除
    A = X + Y  # 当不再需要时，分配将被复用
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[10.488976  ,  4.153824  ,  6.9177847 , -0.20857757,  4.556662  ],
       [ 7.6709642 ,  3.0006697 ,  2.2487464 ,  1.7624911 ,  7.7171993 ],
       [ 6.1307464 ,  1.0036516 , -0.02064353,  5.4354377 ,  2.7916303 ]],
      dtype=float32)>

## tensor变为其他类型

In [88]:
A = tf.ones([3,5])
O = A.numpy()
print(type(O), O)
C = tf.constant(A)
print(type(C))


<class 'numpy.ndarray'> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


**重要**：要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
对constant和variable都需要先转为numpy在进行提取标量的计算。

In [89]:
B = tf.constant([4.6]).numpy()
B, B.item(), float(B), int(B)


(array([4.6], dtype=float32), 4.599999904632568, 4.599999904632568, 4)

In [90]:
V = tf.Variable([4.4]).numpy()
V, V.item(), float(V), int(V)

(array([4.4], dtype=float32), 4.400000095367432, 4.400000095367432, 4)

## 降维

降维是通过按行或者按列进行求和/平均值等方式来实现。

In [91]:
import tensorflow as tf

X = tf.random.normal(shape=[3,5])
Y = tf.ones([3,5])
X, Y

(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-1.7603735 , -0.3856228 , -0.17601512,  0.8873603 , -1.0727581 ],
        [-1.8786201 , -1.5494004 ,  1.3354777 , -1.0904859 , -0.98799276],
        [ 0.88038915, -1.6967478 ,  0.84404236, -1.2167649 , -1.7032427 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>)

axis=0表示按照列来进行求和。
axis=1按照行来进行求和。

In [92]:
A_sum_axis0 = tf.reduce_sum(Y, axis=0)
A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([3., 3., 3., 3., 3.], dtype=float32)>,
 TensorShape([5]))

In [93]:
A_sum_axis1 = tf.reduce_sum(Y, axis=1)
A_sum_axis1, A_sum_axis1.shape

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 5., 5.], dtype=float32)>,
 TensorShape([3]))

注意，可以指定降维的坐标轴。这里是二维的所以轴只有0和1。对于更高维的可以指定更多的坐标轴。

In [94]:
tf.reduce_sum(Y, axis=[0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

## 非降维求和

使用的参数是keepdims=True。

In [95]:
sum_A = tf.reduce_sum(Y, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[5.],
       [5.],
       [5.]], dtype=float32)>

## 按指定轴进行累积求和

这种操作的详细说明：第一行的值是自己。第二行是第一行的值加上第二行的值。第三行是更新后第二行的值再加上第三行的值。以此类推。

In [96]:
tf.cumsum(Y, axis=0)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]], dtype=float32)>

## 矩阵与向量之间的乘法

要求$\boldsymbol{A} \in \mathbb{R}^{m \times n}$和$\boldsymbol{x} \in \mathbb{R}^n$。注意A的列数和x的元素个数相同。得到的结果$\boldsymbol{Ax} \in \mathbb{R}^{m \times 1}$。

In [97]:

A = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
# B = tf.constant([[1],[2],[3]])
B = tf.constant([[1,2,3]])
A.shape, B.shape

(TensorShape([3, 3]), TensorShape([1, 3]))

In [98]:
tf.linalg.matvec(A, B)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[14, 32, 50]])>

## 范数

[相关的数学定义和说明详见](../../mathematics/LinearAlgebra.md)

在深度学习中，我们经常试图解决优化问题： 最大化分配给观测数据的概率; 最小化预测和真实观测之间的距离。 用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离。 目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。

In [99]:
# 定义计算所需要的向量和矩阵
import tensorflow as tf
x = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
A = tf.random.normal([3,4])

1. 对向量计算$L_1$范数

In [100]:
tf.reduce_sum(tf.abs(x))

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

2. 对向量计算$L_2$范数

必须要求向量中元素不是int类型，也就是必须是float类型。

In [101]:
tf.norm(x)

<tf.Tensor: shape=(), dtype=float32, numpy=7.4161983>

3. 对矩阵计算$L_F$范数

In [102]:
tf.norm(A)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7382605>

## 向量之间点积（Dot Product）

给定两个向量$\boldsymbol{x}, \boldsymbol{y} \in \mathbb{R}^d$，它们的点积（dot product）$\boldsymbol{x}^T \boldsymbol{y}$（或$<\boldsymbol{x}, \boldsymbol{y}>$）是相同位置的按元素乘积的和：$\sum\limits_{i=1}^dx_iy_i$

tf.tensordot有点特别，使用x_1和y_1计算时，与tf.reduce_sum(x_1 * y_1)的计算结果不一样。应该是和tf.tensordot的定义有关。而且特别的和axes这个参数有关。

In [103]:
x_1 = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
y_1 = tf.random.normal([5,1])
tf.tensordot(x_1, y_1, axes=1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-4.8162303], dtype=float32)>

In [104]:
tf.reduce_sum(x_1 * y_1)

<tf.Tensor: shape=(), dtype=float32, numpy=-7.6646547>

In [105]:
x_2 = tf.constant([0, 1.0, 2.0, 3.0])
y_2 = tf.constant([1.0, 1.0, 1.0, 1.0])
tf.tensordot(x_2, y_2, axes=1)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [106]:
y_2.shape

TensorShape([4])

In [107]:
x_2 = tf.constant([0, 1.0, 2.0, 3.0])
y_2 = tf.constant([[1.0], [1.0], [1.0], [1.0]])
tf.tensordot(x_2, y_2, axes=1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>

In [108]:
y_2.shape

TensorShape([4, 1])

In [109]:
# help(tf.tensordot)

In [110]:
tf.reduce_sum(x_2 * y_2)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>